### ISSUE TITLE
Please make LICENSE

### ISSUE THREAD

**Issue by try46** [Lapua/fresemi#2]
What happens to the copyright for this repository?
I think that it is necessary for the license for this repository to be specified.
Please tell.

**Comment by Lapua** [comment]
It is impossible to describe about this repository's licence. Because it is dynamic licence. The licence is changed by my mood frequently. If my feeling is happy, it is free licence. Otherwise,this codes cost much money. Thank you for reading my poor English sentences.

**Comment by try46** [comment]
OK...
Thank you for your reply
